version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: joao
      MONGO_INITDB_ROOT_PASSWORD: 123123
    volumes:
      - mongodb-data:/data/db
  
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672" # Porta para o painel de administração baseado em web
      - "5672:5672"   # Porta AMQP
    environment:
      RABBITMQ_DEFAULT_USER: joao
      RABBITMQ_DEFAULT_PASS: 123123
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  mongodb-data:
  rabbitmq-data:
